#include <iostream>
#include <vector>
#include <algorithm>

using namespace std;

// [Include the KosarajuSCC struct here exactly as defined in Template 1]
struct KosarajuSCC {
    int n, scc_count;
    vector<vector<int>> adj, rev_adj;
    vector<int> order, scc_id;
    vector<bool> visited;

    KosarajuSCC(int n) : n(n), scc_count(0), adj(n), rev_adj(n), scc_id(n, -1), visited(n, false) {}
    void add_edge(int u, int v) { adj[u].push_back(v); rev_adj[v].push_back(u); }
    void dfs1(int u) { visited[u] = true; for (int v : adj[u]) if (!visited[v]) dfs1(v); order.push_back(u); }
    void dfs2(int u) { visited[u] = true; scc_id[u] = scc_count; for (int v : rev_adj[u]) if (!visited[v]) dfs2(v); }
    void build_sccs() {
        fill(visited.begin(), visited.end(), false);
        for (int i = 0; i < n; i++) if (!visited[i]) dfs1(i);
        fill(visited.begin(), visited.end(), false);
        for (int i = n - 1; i >= 0; i--) {
            int u = order[i];
            if (!visited[u]) { dfs2(u); scc_count++; }
        }
    }
};

/**
 * Condenses the graph into a DAG using the SCCs generated by Kosaraju's.
 * 
 * @param kosa A completed KosarajuSCC object (after build_sccs() is called).
 * @return A new adjacency list representing the DAG where each node is an SCC.
 */
vector<vector<int>> build_condensation_dag(const KosarajuSCC& kosa) {
    int num_sccs = kosa.scc_count;
    vector<vector<int>> dag(num_sccs);
    
    for (int u = 0; u < kosa.n; ++u) {
        for (int v : kosa.adj[u]) {
            // If u and v belong to DIFFERENT components, add a directed edge between the SCCs
            if (kosa.scc_id[u] != kosa.scc_id[v]) {
                dag[kosa.scc_id[u]].push_back(kosa.scc_id[v]);
            }
        }
    }
    
    // Sort and unique to remove duplicate edges between the same SCCs
    for (int i = 0; i < num_sccs; ++i) {
        sort(dag[i].begin(), dag[i].end());
        dag[i].erase(unique(dag[i].begin(), dag[i].end()), dag[i].end());
    }
    
    return dag;
}

// ---------------------------------------------------------
// Example Usage
// ---------------------------------------------------------
int main() {
    int n = 4;
    KosarajuSCC kosa(n);
    
    // Graph: 0 -> 1 -> 0 (SCC 0), 2 -> 3 -> 2 (SCC 1)
    // Cross edges: 0 -> 2, 1 -> 3
    kosa.add_edge(0, 1); kosa.add_edge(1, 0);
    kosa.add_edge(2, 3); kosa.add_edge(3, 2);
    kosa.add_edge(0, 2);
    kosa.add_edge(1, 3);
    
    kosa.build_sccs();
    
    // Build the DAG
    vector<vector<int>> condensed_dag = build_condensation_dag(kosa);
    
    cout << "Condensed DAG Edges (Super-node connections):\n";
    for (int u = 0; u < kosa.scc_count; ++u) {
        for (int v : condensed_dag[u]) {
            cout << "SCC " << u << " -> SCC " << v << "\n";
        }
    }
    
    return 0;
}
